task: cross_tissue
data_path: '/home/akhoeini/scratch/scRNAseq/processed/'
source: [['cross_tissue_1/pancreas_baron_human.h5ad', 'cross_tissue_1/pancreas_segerstolp_human.h5ad'], ['cross_tissue_2/pancreas_baron_mouse.h5ad', 'cross_tissue_2/pancreas_tm_mouse.h5ad']]
target: ['cross_tissue_1/kidney_park_human.h5ad', 'cross_tissue_2/kidney_tm_mouse.h5ad']
reps: 3 # experiment repetition
shuffle_data: True
cuda: True
fix_seed: True
seed: 123
pretrain: True
cluster_alignment: True
z_dim: 100 # latent representation dim
h_dim: [1024, 256]  # hidden layer dim
epochs: 200
epochs_pretrain: 40
learning_rate: 0.005
learning_rate_pretrain: 0.0005
lr_scheduler_step: 50
lr_scheduler_gamma: 0.1
intercluster_const: 0.2
simclr_noise: 0.1
eval_freq: 128



### Checkpoint
note: train
snapshot: './output/checkpoints'

tensorboard: False
verbose: True